<!DOCTYPE html>
<html lang="en">               
    <head>                                  
        <meta charset="utf-8">                                  
        <title>FlexScore - Frequently Asked Questions                    
        </title>                                  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">                                  
        <meta name="description" content="FlexScore gives you total financial clarity wrapped up in a single score. It's fast, free, and even a little fun.">
        <meta name="author" content="FlexScore">
        <meta name="apple-itunes-app" content="app-id=916633885">
        <meta property="og:title" content="FlexScore - Frequently Asked Questions ">
        <meta property="og:url" content="https://www.flexscore.com/faqs">
        <meta property="og:locale" content="en_US">
        <meta property="og:description" content="FlexScore gives you total financial clarity wrapped up in a single score. It's fast, free, and even a little fun.">
        <meta property="og:image" content="https://www.flexscore.com/ui/images/home_laptop.png">
        <meta content="u3kX0jqV2_YEhCCIzKks2-P3Ws45R2ESrSsLQkRCiaQ" name="google-site-verification">
        <meta content="xZIdeyYAE_R97c0H6OGvkHeVWEI" name="alexaVerifyID">
        <meta name="msvalidate.01" content="1967933DCC3E8DF336994671EAAE77FD" />                 
        <script type="text/javascript" src="./uiconf.js"></script>
        <!-- Le styles -->                                        
        <link href="./ui/css/bootstrap/bootstrap.css" rel="stylesheet" />                                                                  
        <link rel="stylesheet" href="./ui/css/jquery.bxslider2.css?v=1" type="text/css" media="screen" />                                  
        <link href="./ui/css/bootstrap/bootstrap-responsive.css" rel="stylesheet" />
        <link rel="stylesheet" href="./ui/css/fonts.css" type="text/css" />                                  
        <link rel="stylesheet" href="./ui/css/bootstrap/flexscore.css" type="text/css" media="screen" />       
        <link rel="stylesheet" href="./ui/css/bootstrap/bootstrap-buttons-ls.css" type="text/css" />       
		<link href="./ui/css/bootstrap/bootstrap-multiselect.css" rel="stylesheet" />
        <link href="<?php echo $baseurl ?>ui/css/multiselectDropdown.css" rel="stylesheet" />
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->                     
        <!--[if lt IE 9]>
                          <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
                        <![endif]-->                      
        <!-- Fav and touch icons -->   
        <style type="text/css">body {padding-top: 60px;}                                   
        </style>                                           
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="ico/apple-touch-icon-144-precomposed.png">                                  
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="ico/apple-touch-icon-114-precomposed.png">                                  
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="ico/apple-touch-icon-72-precomposed.png">                                  
        <link rel="apple-touch-icon-precomposed" href="ico/apple-touch-icon-57-precomposed.png">                                  
        <link rel="shortcut icon" href="./ui/images/favicon.png">                    
    </head>                    
    <body id="body" class="white" style="display:none">
        <a id="securityFAQ" name="securityFAQ"></a>
        <input type="hidden" id="currentPage" value="faqs">
        <div class="textureBackgroundWrap">                                   
            <div id="mainHeader">
            </div>
           <div id="navSpacer" class="visible-phone">&nbsp;
            </div>
            <div id="navSpacerShort" class="hidden-phone">&nbsp;
            </div>                
            <div class="container">     
                <div id="homeBg" style="background:none">
                </div>                                 
                <div class="mainBody faq">                                                   
                    <div class="row-fluid">                                                                                                                     
                        <h1 class="infoH1">Frequently Asked Questions</h1>

                    </div>                                               
                    <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                    </div> 
                    <div class="hdn">
                        <h3>
                            Contents
                        </h3>  
                        <div class="hidden-phone">
                            <div>
                                <a href="javascript:$.scrollTo( $('#section1Land'), 800, {'axis':'y'} );">Security Of Data</a>
                            </div>
                            <div>
                                <a href="javascript:$.scrollTo( $('#section2Land'), 800, {'axis':'y'} );">Financial Advice Engine</a>
                            </div>
                            <div>
                                <a href="javascript:$.scrollTo( $('#section3Land'), 800, {'axis':'y'} );">General Q&amp;A</a>
                            </div>
                            <div>
                                <a href="javascript:$.scrollTo( $('#section3Land'), 800, {'axis':'y'} );">Connecting Accounts / CashEdge FAQ's</a>
                            </div>
                        </div>
                        <div class="visible-phone">
                            <div>
                                &nbsp;<a href="javascript:$.scrollTo( $('#section1LandMobile'), 800, {'axis':'y'} );">Security Of Data</a>
                            </div>
                            <div>
                                &nbsp;<a href="javascript:$.scrollTo( $('#section2LandMobile'), 800, {'axis':'y'} );">Financial Advice Engine</a>
                            </div>
                            <div>
                                &nbsp;<a href="javascript:$.scrollTo( $('#section3LandMobile'), 800, {'axis':'y'} );">General Q&amp;A</a>
                            </div>
                            <div>
                                &nbsp;<a href="javascript:$.scrollTo( $('#section3LandMobile'), 800, {'axis':'y'} );">Connecting Accounts / CashEdge FAQ's</a>
                            </div>
                        </div>
                    </div>
                    <div style="position:relative">
                        <div style="top:-80px;position:absolute" id="section1Land" class="clearOnly">
                            <a href="#section1Land"></a>
                        </div>
                        <div style="top:-50px;position:absolute" id="section1LandMobile" class="clearOnly">
                            <a href="#section1LandMobile"></a>
                        </div>
                    </div>
                    <h3>
                        Security Of Data
                    </h3>   
                    <div id="faqAccordion" class="accordion">                                         
                        <!-- faq item 1 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">    
                                <a href="#collapse01" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow"></div>                                                  
                                    Is my data secure?
                                </a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse01">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">     
                                    <p>The short answer: Yes. The long answer: FlexScore uses bank-grade security to protect your data. SHA-256 Encryption and 256-bit Secure Socket Layer (SSL) technology keeps your data private and secure. Also, Norton and McAfee regularly scan our websites to make sure that our security measures are running at their full capacity and privacy policy is followed.
                                    </p>                                                     
                                    <p>
                                        In addition to the electronic security, your data is also protected by some serious physical measures. Security personnel monitor the system 24 hours a day, 7 days a week. Access to servers requires multiple levels of authentication, including biometrics (hand print scan) and identity authentication.
                                    </p>                  
                                    <p>
                                        Finally, while FlexScore lets you view all of your financial accounts, no one—not you, nor us, nor anyone—can make changes to those accounts through FlexScore.
                                    </p>            
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 2 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse02" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Why does FlexScore need my username and password for my financial accounts?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse02">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                                                                                                                                                                                                                                    
                                    <p>
                                        We need your online usernames and passwords for all financial accounts so that we can give you the best financial advice for your specific circumstances. Using our account aggregation service (CashEdge) we securely connect with your bank, credit card companies, brokerage firms, retirement plan accounts, etc. The information we need is then automatically downloaded into our advice engine daily. This way, you don't have to constantly update us. Instead, we update you!
                                    </p>                                                                                                                                                                                                           
                                </div>
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 3 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse03" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Do you store my usernames and passwords for my financial accounts on your servers?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse03">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        No, this information is not kept on our servers. Your login credentials are stored securely in a separate database at FiServ using institutional-level encryption and in accordance with our Privacy Policy and Terms of Use. Additionally, no employees of FlexScore can see your credentials.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 4 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse04" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Can't identity thieves steal my identity more easily if I have all of my financial information in one place?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse04">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        No. Identity thieves need information that we don't ask for—like your social security number, telephone number, or address. Also, we never ask for any personal financial account numbers. The level of information FlexScore needs is the same as what is found on the financial company websites you already use. At no time do we ask you for information that would be required for a hacker to steal your identity, such as your full name, financial account numbers, credit card numbers, billing address, etc.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                
                        <!-- faq item 5 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse05" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Can FlexScore employees view my bank account numbers or credit card numbers?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse05">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Based on our Terms of Use and Privacy Policy, your information may only be seen by technicians who would work within our system to help solve technical difficulties or improve the service. As part of the normal due diligence of running a technology company like FlexScore, we must ensure that our advice engine is always operable and being maintained to the highest standards. Should one of these technicians come to view financial information, they will not be able to associate it to a specific user or account.
                                    </p>                                                                                      
                                </div>                                                         
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                
                        <!-- faq item 6 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse06" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>            
                                    What are some good security practices I should embrace if I'm a still little nervous about having all my financial data in one place?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse06">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <div>
                                        <div class="floatL">1.</div>
                                        <div class="floatL" style="padding-left:10px;width:90%">Don’t keep your social security number anywhere where others can see it, or enter it into any website unless you are ABSOLUTELY certain you know the reason to do so. Remember, FlexScore will never ask you for your social security number.
                                        </div>
                                        <div class="clearEverything tenpx"></div>
                                    </div>                 
                                    <div>   
                                        <div class="floatL">2.</div>
                                        <div class="floatL" style="padding-left:10px;width:90%">Don't use simple passwords that can easily be guessed. Use multiple characters including letters (both upper and lower case), numbers, and symbols.
                                        </div> 
                                        <div class="clearEverything tenpx"></div>
                                    </div>                    
                                    <div>
                                        <div class="floatL">3.</div>
                                        <div class="floatL" style="padding-left:10px;width:90%">Don't use a computer without virus protection and a firewall.
                                        </div>                                                              
                                        <div class="clearEverything tenpx"></div>
                                    </div>
                                </div>                    
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                  
                        <!-- faq item 7 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse07" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What if someone gets access to my FlexScore log in information? Do I now have to get new bank accounts and credit cards numbers for protection?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse07">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Remember that all the data visible to FlexScore is considered view/read only. This means that you (or anyone acting as you) cannot use FlexScore to trade or change investments, move money, change beneficiaries, or send out payments via bank accounts. You must still use your online login credentials for your respective financial accounts to make that happen. Therefore, in the very unlikely event that someone uses your FlexScore login credentials, they will only be able to "see" things and not be able to "do" things.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                  
                        <!-- faq item 8 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse08" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Do you sell my financial data or personal information to anybody?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse08">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        No, we don't sell your information to anyone. We do share information with companies who we recommend you use to advance your financial future. And that information is only shared once you have given us permission to do so, and only for purposes of expediting the placement of products or solutions for your benefit.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                                                                                     
                        <!-- faq item 9 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse09" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Will you ever start charging for your service?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse09">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        We will never charge for the level of service and advice FlexScore delivers currently. At some point in the future we may add a "premium" service that would offer a separate level of services and products for those users who are interested.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>      
                    </div>
                    <div style="position:relative">
                        <div style="top:-80px;position:absolute" id="section2Land" class="clearOnly">
                            <a href="#section2Land"></a>
                        </div>
                        <div style="top:-50px;position:absolute" id="section2LandMobile" class="clearOnly">
                            <a href="#section2LandMobile"></a>
                        </div>
                    </div>
                    <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                    </div>     
                    <h3>
                        Financial Advice Engine
                    </h3>   
                    <div id="faqAccordion2" class="accordion">                                         
                        <!-- faq item 1 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse10" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Is your advice unbiased?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse10">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Yes, all our advice is unbiased and our only boss is you. The advice you receive is based on your goals, financial planning standards, and some basic mathematical formulas. So, the only bias you’ll find is our unwavering desire to help you achieve financial freedom.
                                    </p>                                                     
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 2 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse11" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    How do you rank investments?</a>                                                      
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse11">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                                                                                                                                                                                                                                    
                                    <p>
                                        We consider an investment worthy of recommendation if it filters through our ranking criteria that screen for proven, consistent investment strategies with the highest fiduciary standards. For a complete explanation of how we do this, please see <a href="./ui/content/InvestmentFormula.pdf" target="_blank">Investment Formula</a>.
                                    </p>                                                                                                                                                                                                           
                                </div>
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 3 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse12" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Can you give me the technical details behind your algorithm advice engine?</a>                                          
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse12">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Yes. But then we'd have to kill you. Just kidding. But, seriously, depending on what you mean by "technical details," you might be looking for <a href="./ui/content/TheAlgorithm.pdf" target="_blank">The Algorithm</a> or the <a href="./ui/content/InvestmentFormula.pdf" target="_blank">Investment Formula</a>. 
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 4 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse13" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Who are the companies that provide fulfillment of the action steps we need to take?</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse13">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        We use a host of companies to fulfill our custom financial advice. The companies range from large, public entities, to smaller, private companies. The common denominator amongst them is that we’ve found them to be excellent at customer service, problem solving, and using technology to remotely fulfill your needs quickly and efficiently. All of the companies we refer you to are third parties and separate from FlexScore.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                
                        <!-- faq item 5 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse14" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    How do you know which accounts I will use to fund specific goals? Isn't this important for you to know?</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse14">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Our proprietary GoalLogic<sup>SM</sup> technology determines the type of account that works best to fund your specific goal. For example, if you wanted to purchase a home and needed a down payment of $50,000, you might have that money in more than one account. Suppose you had $100,000 in a 401(k) retirement account and $100,000 in a savings account. Given these circumstances, we'd advise you to take the money from a non-retirement account, since a withdraw from a retirement account is generally not suitable for that purpose. The same goes for other goals and more complex circumstances. We help you fund your immediate goals in the most financially smart way possible.                  
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                               
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>          
                        <!-- faq item 6 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse21" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    When it comes to FlexScore's 10 Levels of Risk Tolerance, how did you determine the return and risk estimates?</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse21">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        We use software that optimizes maximum levels of investment return for any given amount of investment risk.  As most people recognize, the more risk you take, the higher the potential return on your money.  However, without the proper approach, many investors take unnecessary risks for the amount of investment return they are seeking.  It's sort of like driving 100 miles per hour on the freeway.  Sure, you might arrive at your destination earlier, but that's only if you're still alive or not in jail.  When it comes to your money, so that you take only as much risk as needed (and not a smidge more!), we use the research of New Frontier Advisors delivered through fi360 software.  <a href="./ui/content/CapitalMarketInputs.pdf" target="_blank">Click Here</a> to read about the full methodology and capital markets assumptions.
                                    </p>                                                                                   
                                </div>                                                                          
                            </div>                                                                        
                        </div>           
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>          
                        <!-- faq item 7 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse22" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What is the maximum score in FlexScore?</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse22">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        The best you can do is 1,000 points.  It should be everyone's goal.  Once you have 1,000 points, that means you have a large enough nest egg to live the rest of your life without having to work any longer.  It means that you've adequately protected your risks and have financial behaviors in place that will likely sustain you forever.     
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>           
                    </div>
                    <div style="position:relative">
                        <div style="top:-80px;position:absolute" id="section3Land" class="clearOnly">
                            <a href="#section3Land"></a>
                        </div>
                        <div style="top:-50px;position:absolute" id="section3LandMobile" class="clearOnly">
                            <a href="#section3LandMobile"></a>
                        </div>
                    </div>
                    <h3>
                        General Q&amp;A
                    </h3>   
                    <div id="faqAccordion3" class="accordion">                                         
                        <!-- faq item 1 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse15" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Do banks and other companies use FlexScore like the FICO Score?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse15">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Not yet, but our goal is to make your FlexScore as prevalent and useful as your FICO Score. This would allow banks and any other financial institution that need to know how well you are doing financially (not just with your credit) one more way to verify personal financial responsibility. 
                                    </p>                                                     
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 2 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse16" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    How does FlexScore make money?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse16">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                                                                                                                                                                                                                                    
                                    <p>
                                        We make money from referral partners you use to complete financial advice action items. Because completing these action items will improve your FlexScore (and your financial life), we are confident that many users will use these partners. This is why we don't make you pay an upfront fee or monthly subscription cost.
                                    </p>                                                                                                                                                                                                           
                                </div>
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 3 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse17" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Whom can I speak to should I have questions that aren't answered on the site?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse17">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Please feel free to ask us any question via our Help Section. We will answer your question within 24 hours of the next business day your question is received.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                         
                        <!-- faq item 4 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse18" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Where's the small print? I know there must be something I'm missing.</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse18">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        All of the so-called "small print" can be found in our <a href="./ui/content/FormADV.pdf" target="_blank">ADV Part 2 Brochure</a>, <a href="./terms" target="_blank">Terms of Use</a>, or <a href="./privacy" target="_blank">Privacy Policy</a>. You'll find nothing hidden or surprising here, just the facts.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                
                        <!-- faq item 5 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse19" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Does FlexScore rely on any third party data?</a>
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse19">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Yes, we rely on third party data from reputable companies like Morningstar, Lipper, Klein Decisions, CalcXML, fi360, and Broadbridge - Forefield to run our advice engine and provide friendly communication about how to improve financially.
                                    </p>                                                                                   
                                </div>                                                                        
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                
                        <!-- faq item 6 -->                                             
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse20" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    Why do I AND my spouse have to get a FlexScore…if we share all of our money, should one score be good enough?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse20">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        There is no such thing as a combined or joint FlexScore. In the same way individuals have unique credit scores, all users will have their own unique FlexScore. Again, like your credit score, you and your spouse may have very similar scores. But, we all have different moving parts in our lives, so FlexScore rates each person's situation independently. Having a FlexScore that is customized for your individual needs is essential.
                                    </p>
                                </div>
                            </div>                                                                        
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                  
                    </div>
                    <h3>
                        Connecting Accounts / CashEdge FAQ's<a id="connectingAccounts" name="connectingAccounts"></a>
                    </h3>   
                    <div id="faqAccordion4" class="accordion">                                         
                        <!-- faq item 1 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse23" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What is Connecting Accounts?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse23">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        Wouldn’t it be great if you had an automated financial advice machine that monitors your financial situation 24/7 and gives you advice to improve your situation customized for your needs?  Well, good news….that’s what FlexScore is!  So, to make the advice as accurate as possible, by connecting your financial accounts to your FlexScore profile you will not have to manually update the values each month.  If fact, connecting your accounts allows for us to keep an eye on your updated values every single day.  That is better than what the average human can do.  Don’t be average.
                                    </p>                                                     
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 1 -->                                              
                        <!-- faq item 2 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse24" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    How Does it Work?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse24">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        We use a technology called AllData® Aggregation from Fiserv, the industry's leading account aggregation service.  It provides the engine for you to build a comprehensive view of your finances.  This allows FlexScore to aggregate account data from virtually any online financial source (more than 13,000 financial institutions) — including investment accounts, employee retirement plans, mortgages, insurance, banking, credit cards, annuities and more.
                                    </p>    
                                    <p>
                                        By using your login credentials just as you would on your financial institution’s website, we connect securely to your financial institution and download only pertinent information such as your account values.  We use the same security protocols that safeguard banking websites across the web, protecting personal information like user names and passwords, as well as account and transaction data.
                                    </p>
                                    <p>
                                        For more information on Security, see our <a href="#securityFAQ">FAQ on Security</a>.
                                    </p>
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 2 -->                                              
                        <!-- faq item 3 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse25" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What About Security Questions / Images / PIN’s / Etc.?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse25">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        If your financial institution requires you to use security questions, images, a PIN code, or similar security features in addition to your password, we can handle that.  When connecting to your financial institution, they’ll send us the information they need for you to provide.  You’ll then be prompted within the FlexScore website to provide this information.
                                    </p>    
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 3 -->                                              
                        <!-- faq item 4 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse26" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What if my Account will not Connect?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse26">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        If you are unable to connect your account, first check the notifications menu at the top of the screen when logged in to your account.  If you have notifications regarding the connection of your account, there will be a small red box with a number in it, indicating the number of notifications you have.  Search through this list to see if you are being prompted to either re-enter login credentials, answer security questions, or perform any function related to the connecting of your accounts.
                                    </p>  
                                    <p>
                                        If there are no notifications regarding your account connections, please contact Support by using the purple box on the right side of the screen when logged in to your account, or email support@flexscore.com and describe your situation.  The more information you can give us, the faster we can fix it.  Try to include the name of your financial institution, the website url you use to login (please <strong>DO NOT</strong> give us your login credentials), and a brief description of the issue.  We’ll respond ASAP.
                                    </p>
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 4 --> 
                        <!-- faq item 5 -->                                              
                        <div class="row-fluid allRound smallGlow accordion-group">                                                                               
                            <div class="accordion-heading pad5">                                                                                  
                                <a href="#collapse27" data-parent="#faqAccordion" data-toggle="collapse" class="accordion-toggle collapsed">                                                  
                                    <div class="floatL faqArrow">                                                                                                                                                                                                                                                                                                   
                                    </div>                                                  
                                    What if I’m Not Sure Which Search Result is my Financial Institution?</a>                                                                        
                            </div>                                                                        
                            <div class="accordion-body collapse mediumGray roundBottom" id="collapse27">                                                                                  
                                <div class="accordion-inner faqBody roundBottom">                                                  
                                    <p>
                                        If you search for your financial institution, get multiple results, and then are left wondering which option to choose, try the first few results.  We’ve optimized the results to show the most common toward the top.  If you are still having trouble, please contact support@flexscore.com and let us know the website url you use to login (please <strong>DO NOT</strong> give us your login credentials).  With this information, we’ll tell you which result to choose.
                                    </p>  
                                </div>                                                                        
                            </div>                                                                            
                        </div>                                              
                        <div class="clearEverything tenpx">&nbsp;                                                                                                                                    
                        </div>                                            
                        <!-- faq item 5 --> 
                    </div>                    
                    <!-- contact support -->                                                                    
                    <div class="row-fluid">                                                                      
                        <div class="span12">                                                                                   
                            <div class="contactSupport allRound">                                                                                                                                                                                                                   
                                <div class="csText floatL">                                                                                                                                                              
                                    <span>Need help?                                                                                                                          
                                    </span>
                                </div> 
                                <button id="supportLCBtn" type="submit" onclick="javascript:window.location = 'mailto:support@flexscore.com';
                                        return false;" class="lsPillBtnGreen btn btn-success">&nbsp;Contact Support&nbsp;</button>             
                            </div>                                                                       
                        </div>                                                           
                    </div>                                                                                                                                                    
                    <div class="clearEverything tenpx">&nbsp;                                                                                                                              
                    </div>                      
                </div>                           
            </div>                                                                                                                                   
            <div class="clearEverything tenpx">                                         
            </div>                             
        </div>                   
        <div class="vSpace hidden-phone">&nbsp;
        </div>                  
        <!-- container -->                               
        <div class="container"> 
            <div id="darkBackground" class="hdn"></div>
            <div id="comparisonBox" class="hdn">
            </div>
            <div id="comparisonBoxHome" class="hdn homeComparison">
                <!-- TABBED CONTENT -->
                <div id="signIn" class="row-fluid hdn dialogContent">
                    <!-- tabs -->
                    <ul class="nav nav-tabs">
                        <li id="signupLink" class="active">
                            <a id="signuptab" data-toggle="tab" href="#signupUser">Sign Up </a>
                        </li>
                        <li id="signinLink">
                            <a id="signintab" data-toggle="tab" href="#loginUser">Sign In</a>
                        </li>
                        <li id="signupAdvisorLink">
                            <a id="signupadvisortab" data-toggle="tab" href="#advisorSignup">For Advisor</a>
                        </li>
                    </ul>
                    <div class="content tab-content">
                        <!-- SIGN UP TAB -->
                        <div class="tab-pane fade active in" id="signupUser">
                        </div>
                        <!-- SIGN IN TAB -->
                        <div class="tab-pane fade" id="loginUser">
                        </div>
                        <!-- SIGNUP ADVISOR TAB -->
                        <div class="tab-pane fade" id="advisorSignup">
                        </div>
                    </div>
                    <div class="clearEverything">
                    </div>
                </div>
            </div>     
            <div id="profileBox" class="hdn">
                <div id="profileContents">
                </div>
            </div>
            <div id="notificationBox" class="hdn">
                <div id="notificationContents">
                </div>
                <div class="profileBottomRow roundBottom">               
                    <div class="clearEverything">&nbsp;         
                    </div>               
                    <div class="clearEverything">&nbsp;         
                    </div>     
                </div>
            </div>
            <div id="myAdvisorBox" class="hdn">
                <div id="myAdvisorContents">
                </div>
            </div>
            <div class="visible-phone tenpx"></div>
            <div id="mainFooter">
            </div>
        </div>                            
        <!-- Placed at the end of the document so the pages load faster -->                
        <script data-main="./ui/js/mindex" src="./ui/js/require-jquery.js"></script>
    </body>
</html>
