<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UrbanAirship' => array($vendorDir . '/urbanairship/urbanairship/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Mustache' => array($vendorDir . '/mustache/mustache/src'),
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
    'Mandrill' => array($vendorDir . '/mandrill/mandrill/src'),
    'Mailchimp' => array($vendorDir . '/mailchimp/mailchimp/src'),
    'Httpful' => array($vendorDir . '/nategood/httpful/src'),
);
